# Testing Adding Groups
POST http://localhost:3000/admin/group
Authorization: token testing
Content-Type: application/json

{
  "slug": "sgoyt",
  "name": "Solitaire Games On Your Table",
  "thread": 986303,
  "imageid": 2373684
}

# Get the groups
GET http://localhost:3000/

# Delete groups
DELETE http://localhost:3000/admin/group/sgoyt
Authorization: token testing

# Add Geeklist To SGOYT
POST http://localhost:3000/admin/group/sgoyt/geeklist
Authorization: token testing
Content-Type: application/json

{
  "id": 233358,
  "year": 2017,
  "month": 12,
  "group_slug": "sgoyt"
}

# Add November
POST http://localhost:3000/admin/group/sgoyt/geeklist
Authorization: token testing
Content-Type: application/json

{
  "id": 231127,
  "year": 2017,
  "month": 11,
  "group_slug": "sgoyt"
}

# Get geeklists
GET http://localhost:3000/group/sgoyt

# Delete geeklist
DELETE http://localhost:3000/admin/group/sgoyt/geeklist/233358
Authorization: token testing

# Get geeklists for updating
GET http://localhost:3000/admin/updating
Authorization: token testing

# Run update
POST http://localhost:3000/admin/update
Authorization: token testing

# Raw Geeklist
GET http://localhost:3000/admin/bgg/geeklist/raw/233358
Authorization: token testing

# Transformed Geeklist
GET http://localhost:3000/admin/bgg/geeklist/233358
Authorization: token testing

# User Stats
GET http://localhost:3000/group/sgoyt/user/Kelsin

# Geeklist Stats
GET http://localhost:3000/group/sgoyt/geeklist/233358

# Game Stats
GET http://localhost:3000/group/sgoyt/game/226502
